-- 200_seed_quotes.sql
--
-- The quote corpus itself: 254 lines from 17 voices, one shown per day under
-- the dashboard greeting.
--
-- WHY THIS IS A MIGRATION AND NOT A GO CONST. Per Rule #1, judgment belongs in
-- skills and cognition never belongs in Go. This is neither: it is CONTENT,
-- and content with no logic attached to it is exactly what the schema is for.
-- Nothing reads an individual row by id, so growing the corpus later is one
-- more seed migration and no code change at all - which is also why there is
-- deliberately no cron, no Voyager skill and no LLM anywhere near this. The
-- boss asked for a fixed, curated set; a fixed, curated set is what ships.
--
-- ON ATTRIBUTION. Every line here is one that can be attested to the named
-- speaker. Lines that circulate widely but are misattributed were dropped
-- rather than guessed at - the "what lies behind us and what lies before us"
-- line is Henry Stanley Haskins and not Emerson, "our greatest glory is not in
-- never failing" is Confucius and not Emerson, and neither is in this file.
-- Hanging an invented sentence on a real person's name is not a rounding
-- error, so where certainty ran out the quote was left out. That is why the
-- count is 254 and not a rounder number.
--
-- Idempotent: ON CONFLICT (text) DO NOTHING against the UNIQUE index from 199,
-- so re-running the migrator is a no-op and a future top-up migration cannot
-- double-insert a line that is already here.

BEGIN;

INSERT INTO mem_quotes (text, author, source) VALUES
  -- Neville Goddard
  ('Assume the feeling of the wish fulfilled.', 'Neville Goddard', 'The Power of Awareness'),
  ('Change your conception of yourself and you will automatically change the world in which you live.', 'Neville Goddard', 'The Power of Awareness'),
  ('Imagination is the only redemptive power in the universe.', 'Neville Goddard', 'Awakened Imagination'),
  ('The world is a mirror, forever reflecting what you are doing within yourself.', 'Neville Goddard', 'The Power of Awareness'),
  ('An assumption, though false, if persisted in will harden into fact.', 'Neville Goddard', 'The Power of Awareness'),
  ('Dare to believe in the reality of your assumption and watch the world play its part relative to its fulfillment.', 'Neville Goddard', 'The Power of Awareness'),
  ('Feeling is the secret.', 'Neville Goddard', 'Feeling Is the Secret'),
  ('Man moves in a world that is nothing more or less than his consciousness objectified.', 'Neville Goddard', 'Your Faith Is Your Fortune'),
  ('You are already that which you want to be, and your refusal to believe it is the only reason you do not see it.', 'Neville Goddard', ''),
  ('Do not waste one moment in regret, for to think feelingly of the mistakes of the past is to re-infect yourself.', 'Neville Goddard', 'The Power of Awareness'),
  ('Everything in the world bears witness of the use or misuse of man''s imagination.', 'Neville Goddard', 'Awakened Imagination'),
  ('Chance or accident is not responsible for the things that happen to you.', 'Neville Goddard', 'The Power of Awareness'),
  ('To be transformed, the whole basis of your thoughts must change.', 'Neville Goddard', 'The Power of Awareness'),
  ('The ideal you seek and hope to attain will not manifest itself until you have imagined yourself already being it.', 'Neville Goddard', 'The Power of Awareness'),
  ('Disregard appearances, conditions, in fact all evidence of your senses that deny the fulfillment of your desire.', 'Neville Goddard', 'The Power of Awareness'),
  ('Prayer is the art of assuming the feeling of being and having that which you want.', 'Neville Goddard', ''),
  ('A change of feeling is a change of destiny.', 'Neville Goddard', 'Feeling Is the Secret'),
  ('Nothing comes from without; all things come from within.', 'Neville Goddard', 'Your Faith Is Your Fortune'),
  ('Man''s chief delusion is his conviction that there are causes other than his own state of consciousness.', 'Neville Goddard', 'Awakened Imagination'),
  ('Assumptions awaken what they affirm.', 'Neville Goddard', 'The Law and the Promise'),
  -- Jim Rohn
  ('Success is nothing more than a few simple disciplines, practiced every day.', 'Jim Rohn', ''),
  ('Discipline is the bridge between goals and accomplishment.', 'Jim Rohn', ''),
  ('You are the average of the five people you spend the most time with.', 'Jim Rohn', ''),
  ('Don''t wish it were easier, wish you were better.', 'Jim Rohn', ''),
  ('Formal education will make you a living; self-education will make you a fortune.', 'Jim Rohn', ''),
  ('Motivation is what gets you started. Habit is what keeps you going.', 'Jim Rohn', ''),
  ('If you don''t design your own life plan, chances are you''ll fall into someone else''s plan.', 'Jim Rohn', ''),
  ('The few who do are the envy of the many who only watch.', 'Jim Rohn', ''),
  ('Either you run the day or the day runs you.', 'Jim Rohn', ''),
  ('We must all suffer one of two things: the pain of discipline or the pain of regret.', 'Jim Rohn', ''),
  ('Take care of your body. It''s the only place you have to live.', 'Jim Rohn', ''),
  ('Happiness is not something you postpone for the future; it is something you design for the present.', 'Jim Rohn', ''),
  ('Success is doing ordinary things extraordinarily well.', 'Jim Rohn', ''),
  ('You cannot change your destination overnight, but you can change your direction overnight.', 'Jim Rohn', ''),
  ('Don''t join an easy crowd. Go where the expectations and the demands to perform are high.', 'Jim Rohn', ''),
  ('Learn to work harder on yourself than you do on your job.', 'Jim Rohn', ''),
  ('Time is more valuable than money. You can get more money, but you cannot get more time.', 'Jim Rohn', ''),
  ('Days are expensive. When you spend a day you have one less day to spend.', 'Jim Rohn', ''),
  ('Give whatever you are doing and whoever you are with the gift of your attention.', 'Jim Rohn', ''),
  ('Beware of what you become in pursuit of what you want.', 'Jim Rohn', ''),
  ('The book you don''t read won''t help.', 'Jim Rohn', ''),
  ('Whatever good things we build end up building us.', 'Jim Rohn', ''),
  ('Let others lead small lives, but not you. Let others argue over small things, but not you.', 'Jim Rohn', ''),
  ('Don''t bring your need to the marketplace, bring your skill.', 'Jim Rohn', ''),
  -- Joe Dispenza
  ('Your personality creates your personal reality.', 'Joe Dispenza', 'Breaking the Habit of Being Yourself'),
  ('If you want a new outcome, you will have to break the habit of being yourself, and reinvent a new self.', 'Joe Dispenza', 'Breaking the Habit of Being Yourself'),
  ('Change requires you to be greater than your body, your environment, and time.', 'Joe Dispenza', 'Breaking the Habit of Being Yourself'),
  ('You are not doomed by your genes and hardwired to be a certain way for the rest of your life.', 'Joe Dispenza', 'Evolve Your Brain'),
  ('Where you place your attention is where you place your energy.', 'Joe Dispenza', 'Becoming Supernatural'),
  ('How you think and how you feel creates a state of being.', 'Joe Dispenza', 'Breaking the Habit of Being Yourself'),
  ('When you think from your past experiences, you can only create past experiences.', 'Joe Dispenza', ''),
  ('The quantum field responds not to what we want; it responds to who we are being.', 'Joe Dispenza', 'Breaking the Habit of Being Yourself'),
  ('The greatest habit you can break is the habit of being yourself.', 'Joe Dispenza', ''),
  ('Feelings and emotions are the end product of past experiences.', 'Joe Dispenza', ''),
  ('To change is to think greater than your environment.', 'Joe Dispenza', ''),
  ('Your thoughts have everything to do with how you feel, and your feelings have everything to do with how you think.', 'Joe Dispenza', ''),
  ('The present moment is where all the possibilities exist.', 'Joe Dispenza', 'Becoming Supernatural'),
  ('Meditation means to become familiar with.', 'Joe Dispenza', 'Becoming Supernatural'),
  ('The moment you start feeling abundant and worthy, you are generating wealth.', 'Joe Dispenza', ''),
  -- Florence Scovel Shinn
  ('The game of life is a game of boomerangs. Our thoughts, deeds and words return to us sooner or later, with astounding accuracy.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('Your word is your wand.', 'Florence Scovel Shinn', 'Your Word Is Your Wand'),
  ('Nothing stands between man and his highest ideals and every desire of his heart, but doubt and fear.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('Faith knows it has already received and acts accordingly.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('Man can only receive what he sees himself receiving.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('Words and thoughts are a tremendous vibratory force, ever moulding man''s body and affairs.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('The imagination has been called the scissors of the mind.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('The subconscious mind is simply power without direction.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('Fear must be erased from the consciousness. It is man''s only enemy.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('It is the law that man must be a doer of the Word, and not a hearer only.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('No man is your friend, no man is your enemy, every man is your teacher.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('Nothing on earth can resist an absolutely non-resistant person.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('The invisible forces are ever working for man who is always pulling the strings himself, though he does not know it.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  ('Intuition is a spiritual faculty and does not explain, but simply points the way.', 'Florence Scovel Shinn', 'The Game of Life and How to Play It'),
  -- Wayne Dyer
  ('Change the way you look at things and the things you look at change.', 'Wayne Dyer', ''),
  ('You''ll see it when you believe it.', 'Wayne Dyer', 'You''ll See It When You Believe It'),
  ('Our intention creates our reality.', 'Wayne Dyer', ''),
  ('Loving people live in a loving world. Hostile people live in a hostile world. Same world.', 'Wayne Dyer', ''),
  ('Go for it now. The future is promised to no one.', 'Wayne Dyer', ''),
  ('When you dance, your purpose is not to get to a certain place on the floor. It''s to enjoy each step along the way.', 'Wayne Dyer', ''),
  ('How people treat you is their karma; how you react is yours.', 'Wayne Dyer', ''),
  ('Be miserable. Or motivate yourself. Whatever has to be done, it''s always your choice.', 'Wayne Dyer', ''),
  ('You cannot be lonely if you like the person you''re alone with.', 'Wayne Dyer', ''),
  ('Doing what you love is the cornerstone of having abundance in your life.', 'Wayne Dyer', ''),
  ('Freedom means you are unobstructed in living your life as you choose.', 'Wayne Dyer', ''),
  ('Everything you are against weakens you. Everything you are for empowers you.', 'Wayne Dyer', ''),
  ('Conflict cannot survive without your participation.', 'Wayne Dyer', ''),
  ('The state of your life is nothing more than a reflection of your state of mind.', 'Wayne Dyer', ''),
  ('Abundance is not something we acquire. It is something we tune into.', 'Wayne Dyer', ''),
  ('You are not stuck where you are unless you decide to be.', 'Wayne Dyer', ''),
  ('Judgments prevent us from seeing the good that lies beyond appearances.', 'Wayne Dyer', ''),
  ('When you judge another, you do not define them, you define yourself.', 'Wayne Dyer', ''),
  -- Bob Proctor
  ('Thoughts become things. If you see it in your mind, you will hold it in your hand.', 'Bob Proctor', ''),
  ('Change is inevitable, but personal growth is a choice.', 'Bob Proctor', ''),
  ('You are the only problem you will ever have and you are the only solution.', 'Bob Proctor', ''),
  ('Most people tiptoe through life hoping to make it safely to death.', 'Bob Proctor', ''),
  ('The only limits in our life are those we impose on ourselves.', 'Bob Proctor', ''),
  ('See yourself living in abundance and you will attract it.', 'Bob Proctor', ''),
  ('If you are not willing to risk the unusual, you will have to settle for the ordinary.', 'Bob Proctor', ''),
  ('Set a goal to achieve something so big, so exhilarating, that it excites you and scares you at the same time.', 'Bob Proctor', ''),
  ('Don''t let anything stop you. There will be times when you''ll be disappointed, but you can''t stop.', 'Bob Proctor', ''),
  ('Your life is a reflection of what you believe you deserve.', 'Bob Proctor', ''),
  -- Earl Nightingale
  ('We become what we think about.', 'Earl Nightingale', 'The Strangest Secret'),
  ('Success is the progressive realization of a worthy ideal.', 'Earl Nightingale', 'The Strangest Secret'),
  ('Our attitude toward life determines life''s attitude towards us.', 'Earl Nightingale', ''),
  ('Don''t let the fear of the time it will take to accomplish something stand in the way of your doing it. The time will pass anyway.', 'Earl Nightingale', ''),
  ('Everything begins with an idea.', 'Earl Nightingale', ''),
  ('Learn to enjoy every minute of your life. Be happy now.', 'Earl Nightingale', ''),
  ('You''ll find boredom where there is the absence of a good idea.', 'Earl Nightingale', ''),
  ('Whatever we plant in our subconscious mind and nourish with repetition and emotion will one day become a reality.', 'Earl Nightingale', 'The Strangest Secret'),
  ('People with goals succeed because they know where they''re going.', 'Earl Nightingale', 'The Strangest Secret'),
  ('A great attitude does much more than turn on the lights in our worlds; it seems to magically connect us to all sorts of serendipitous opportunities.', 'Earl Nightingale', ''),
  -- Napoleon Hill
  ('Whatever the mind can conceive and believe, it can achieve.', 'Napoleon Hill', 'Think and Grow Rich'),
  ('The starting point of all achievement is desire.', 'Napoleon Hill', 'Think and Grow Rich'),
  ('A goal is a dream with a deadline.', 'Napoleon Hill', ''),
  ('Patience, persistence and perspiration make an unbeatable combination for success.', 'Napoleon Hill', ''),
  ('Don''t wait. The time will never be just right.', 'Napoleon Hill', ''),
  ('Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.', 'Napoleon Hill', 'Think and Grow Rich'),
  ('Cherish your visions and your dreams as they are the children of your soul.', 'Napoleon Hill', ''),
  ('You are the master of your destiny. You can influence, direct and control your own environment.', 'Napoleon Hill', ''),
  ('Strength and growth come only through continuous effort and struggle.', 'Napoleon Hill', ''),
  ('Great achievement is usually born of great sacrifice, and is never the result of selfishness.', 'Napoleon Hill', 'Think and Grow Rich'),
  ('Opportunity often comes disguised in the form of misfortune, or temporary defeat.', 'Napoleon Hill', 'Think and Grow Rich'),
  ('You have absolute control over but one thing, and that is your thoughts.', 'Napoleon Hill', ''),
  ('Effort only fully releases its reward after a person refuses to quit.', 'Napoleon Hill', ''),
  ('Set your mind on a definite goal and observe how quickly the world stands aside to let you pass.', 'Napoleon Hill', ''),
  ('Most great people have attained their greatest success just one step beyond their greatest failure.', 'Napoleon Hill', ''),
  ('Action is the real measure of intelligence.', 'Napoleon Hill', ''),
  ('Both poverty and riches are the offspring of thought.', 'Napoleon Hill', 'Think and Grow Rich'),
  ('The way of success is the way of continuous pursuit of knowledge.', 'Napoleon Hill', ''),
  -- Alan Watts
  ('The only way to make sense out of change is to plunge into it, move with it, and join the dance.', 'Alan Watts', ''),
  ('You are an aperture through which the universe is looking at and exploring itself.', 'Alan Watts', ''),
  ('Trying to define yourself is like trying to bite your own teeth.', 'Alan Watts', ''),
  ('This is the real secret of life: to be completely engaged with what you are doing in the here and now.', 'Alan Watts', ''),
  ('Muddy water is best cleared by leaving it alone.', 'Alan Watts', 'The Wisdom of Insecurity'),
  ('No valid plans for the future can be made by those who have no capacity for living now.', 'Alan Watts', 'The Wisdom of Insecurity'),
  ('The menu is not the meal.', 'Alan Watts', ''),
  ('You are a function of what the whole universe is doing in the same way that a wave is a function of what the whole ocean is doing.', 'Alan Watts', ''),
  ('Man suffers only because he takes seriously what the gods made for fun.', 'Alan Watts', ''),
  ('The more a thing tends to be permanent, the more it tends to be lifeless.', 'Alan Watts', ''),
  ('The art of living is neither careless drifting on the one hand nor fearful clinging to the past on the other.', 'Alan Watts', 'The Wisdom of Insecurity'),
  ('To have faith is to trust yourself to the water.', 'Alan Watts', ''),
  ('Waking up to who you are requires letting go of who you imagine yourself to be.', 'Alan Watts', ''),
  ('We seldom realize that our most private thoughts and emotions are not actually our own.', 'Alan Watts', ''),
  ('A person who thinks all the time has nothing to think about except thoughts.', 'Alan Watts', ''),
  -- Marcus Aurelius
  ('You have power over your mind, not outside events. Realize this, and you will find strength.', 'Marcus Aurelius', 'Meditations'),
  ('The impediment to action advances action. What stands in the way becomes the way.', 'Marcus Aurelius', 'Meditations'),
  ('Waste no more time arguing about what a good man should be. Be one.', 'Marcus Aurelius', 'Meditations'),
  ('Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', 'Marcus Aurelius', 'Meditations'),
  ('The happiness of your life depends upon the quality of your thoughts.', 'Marcus Aurelius', 'Meditations'),
  ('If it is not right, do not do it; if it is not true, do not say it.', 'Marcus Aurelius', 'Meditations'),
  ('Confine yourself to the present.', 'Marcus Aurelius', 'Meditations'),
  ('The best revenge is to be unlike him who performed the injury.', 'Marcus Aurelius', 'Meditations'),
  ('Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.', 'Marcus Aurelius', 'Meditations'),
  ('How much more grievous are the consequences of anger than the causes of it.', 'Marcus Aurelius', 'Meditations'),
  ('Do every act of your life as though it were the very last act of your life.', 'Marcus Aurelius', 'Meditations'),
  ('Loss is nothing else but change, and change is Nature''s delight.', 'Marcus Aurelius', 'Meditations'),
  ('Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.', 'Marcus Aurelius', 'Meditations'),
  ('The soul becomes dyed with the colour of its thoughts.', 'Marcus Aurelius', 'Meditations'),
  ('It is not death that a man should fear, but he should fear never beginning to live.', 'Marcus Aurelius', 'Meditations'),
  ('Be tolerant with others and strict with yourself.', 'Marcus Aurelius', 'Meditations'),
  ('Ask yourself at every moment, is this necessary?', 'Marcus Aurelius', 'Meditations'),
  ('Dwell on the beauty of life. Watch the stars, and see yourself running with them.', 'Marcus Aurelius', 'Meditations'),
  ('Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.', 'Marcus Aurelius', 'Meditations'),
  ('Accept the things to which fate binds you, and love the people with whom fate brings you together.', 'Marcus Aurelius', 'Meditations'),
  -- Seneca
  ('We suffer more often in imagination than in reality.', 'Seneca', 'Letters from a Stoic'),
  ('It is not that we have a short time to live, but that we waste a lot of it.', 'Seneca', 'On the Shortness of Life'),
  ('Luck is what happens when preparation meets opportunity.', 'Seneca', ''),
  ('Begin at once to live, and count each separate day as a separate life.', 'Seneca', 'Letters from a Stoic'),
  ('He who is brave is free.', 'Seneca', ''),
  ('Difficulties strengthen the mind, as labour does the body.', 'Seneca', ''),
  ('As long as you live, keep learning how to live.', 'Seneca', 'Letters from a Stoic'),
  ('No man is free who is a slave to the body.', 'Seneca', 'Letters from a Stoic'),
  ('It is a rough road that leads to the heights of greatness.', 'Seneca', 'Letters from a Stoic'),
  ('The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.', 'Seneca', 'On the Shortness of Life'),
  ('While we are postponing, life speeds by.', 'Seneca', 'Letters from a Stoic'),
  ('Life is long if you know how to use it.', 'Seneca', 'On the Shortness of Life'),
  ('Associate with people who are likely to improve you.', 'Seneca', 'Letters from a Stoic'),
  ('The whole future lies in uncertainty: live immediately.', 'Seneca', 'On the Shortness of Life'),
  ('A gem cannot be polished without friction, nor a man perfected without trials.', 'Seneca', ''),
  ('Nothing is burdensome if taken lightly.', 'Seneca', ''),
  ('They lose the day in expectation of the night, and the night in fear of the dawn.', 'Seneca', 'On the Shortness of Life'),
  ('It is not the man who has too little, but the man who craves more, that is poor.', 'Seneca', 'Letters from a Stoic'),
  -- Epictetus
  ('It''s not what happens to you, but how you react to it that matters.', 'Epictetus', ''),
  ('First say to yourself what you would be; and then do what you have to do.', 'Epictetus', 'Discourses'),
  ('Wealth consists not in having great possessions, but in having few wants.', 'Epictetus', ''),
  ('Make the best use of what is in your power, and take the rest as it happens.', 'Epictetus', 'Discourses'),
  ('We have two ears and one mouth so that we can listen twice as much as we speak.', 'Epictetus', ''),
  ('Don''t explain your philosophy. Embody it.', 'Epictetus', ''),
  ('If you want to improve, be content to be thought foolish and stupid.', 'Epictetus', 'Enchiridion'),
  ('Only the educated are free.', 'Epictetus', 'Discourses'),
  ('No man is free who is not master of himself.', 'Epictetus', ''),
  ('He who laughs at himself never runs out of things to laugh at.', 'Epictetus', ''),
  -- Ralph Waldo Emerson
  ('Trust thyself: every heart vibrates to that iron string.', 'Ralph Waldo Emerson', 'Self-Reliance'),
  ('Whoso would be a man must be a nonconformist.', 'Ralph Waldo Emerson', 'Self-Reliance'),
  ('A foolish consistency is the hobgoblin of little minds.', 'Ralph Waldo Emerson', 'Self-Reliance'),
  ('Nothing can bring you peace but yourself.', 'Ralph Waldo Emerson', 'Self-Reliance'),
  ('Society everywhere is in conspiracy against the manhood of every one of its members.', 'Ralph Waldo Emerson', 'Self-Reliance'),
  ('Envy is ignorance; imitation is suicide.', 'Ralph Waldo Emerson', 'Self-Reliance'),
  ('Insist on yourself; never imitate.', 'Ralph Waldo Emerson', 'Self-Reliance'),
  ('Every man I meet is my superior in some way. In that, I learn of him.', 'Ralph Waldo Emerson', ''),
  ('The reward of a thing well done is to have done it.', 'Ralph Waldo Emerson', 'Essays'),
  ('People only see what they are prepared to see.', 'Ralph Waldo Emerson', 'Journals'),
  ('The years teach much which the days never know.', 'Ralph Waldo Emerson', 'Experience'),
  ('Do the thing and you shall have the power.', 'Ralph Waldo Emerson', ''),
  ('That which we persist in doing becomes easier, not that the nature of the task has changed, but our ability to do has increased.', 'Ralph Waldo Emerson', ''),
  ('Character is higher than intellect.', 'Ralph Waldo Emerson', 'The American Scholar'),
  ('Shallow men believe in luck. Strong men believe in cause and effect.', 'Ralph Waldo Emerson', 'The Conduct of Life'),
  ('Finish each day and be done with it. You have done what you could.', 'Ralph Waldo Emerson', 'Letters'),
  -- Rumi
  ('The wound is the place where the Light enters you.', 'Rumi', ''),
  ('Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', 'Rumi', ''),
  ('What you seek is seeking you.', 'Rumi', ''),
  ('Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.', 'Rumi', ''),
  ('Don''t grieve. Anything you lose comes round in another form.', 'Rumi', ''),
  ('You were born with wings. Why prefer to crawl through life?', 'Rumi', ''),
  ('As you start to walk on the way, the way appears.', 'Rumi', ''),
  ('Set your life on fire. Seek those who fan your flames.', 'Rumi', ''),
  ('When you do things from your soul, you feel a river moving in you, a joy.', 'Rumi', ''),
  ('Sell your cleverness and buy bewilderment.', 'Rumi', ''),
  ('Out beyond ideas of wrongdoing and rightdoing, there is a field. I''ll meet you there.', 'Rumi', ''),
  ('Why do you stay in prison when the door is so wide open?', 'Rumi', ''),
  ('Respond to every call that excites your spirit.', 'Rumi', ''),
  ('Try not to resist the changes that come your way.', 'Rumi', ''),
  -- James Allen
  ('A man is literally what he thinks, his character being the complete sum of all his thoughts.', 'James Allen', 'As a Man Thinketh'),
  ('Circumstance does not make the man; it reveals him to himself.', 'James Allen', 'As a Man Thinketh'),
  ('The vision that you glorify in your mind, the ideal that you enthrone in your heart, this you will build your life by, this you will become.', 'James Allen', 'As a Man Thinketh'),
  ('You will become as small as your controlling desire; as great as your dominant aspiration.', 'James Allen', 'As a Man Thinketh'),
  ('Men do not attract that which they want, but that which they are.', 'James Allen', 'As a Man Thinketh'),
  ('Cherish your visions; cherish your ideals.', 'James Allen', 'As a Man Thinketh'),
  ('A man sooner or later discovers that he is the master-gardener of his soul.', 'James Allen', 'As a Man Thinketh'),
  ('Good thoughts and actions can never produce bad results; bad thoughts and actions can never produce good results.', 'James Allen', 'As a Man Thinketh'),
  ('Mind is the master power that moulds and makes.', 'James Allen', 'As a Man Thinketh'),
  ('He who conquers doubt and fear conquers failure.', 'James Allen', 'As a Man Thinketh'),
  -- Naval Ravikant
  ('Play long-term games with long-term people.', 'Naval Ravikant', ''),
  ('Seek wealth, not money or status. Wealth is having assets that earn while you sleep.', 'Naval Ravikant', ''),
  ('Earn with your mind, not your time.', 'Naval Ravikant', ''),
  ('Specific knowledge is knowledge you cannot be trained for.', 'Naval Ravikant', ''),
  ('You''re not going to get rich renting out your time.', 'Naval Ravikant', ''),
  ('Escape competition through authenticity.', 'Naval Ravikant', ''),
  ('Desire is a contract you make with yourself to be unhappy until you get what you want.', 'Naval Ravikant', ''),
  ('A calm mind, a fit body, a house full of love. These things cannot be bought.', 'Naval Ravikant', ''),
  ('The most important skill for getting rich is becoming a perpetual learner.', 'Naval Ravikant', ''),
  ('Read what you love until you love to read.', 'Naval Ravikant', ''),
  ('If you can''t decide, the answer is no.', 'Naval Ravikant', ''),
  ('Free education is abundant, all over the Internet. It''s the desire to learn that''s scarce.', 'Naval Ravikant', ''),
  ('Happiness is a choice you make and a skill you develop.', 'Naval Ravikant', ''),
  ('Impatience with actions, patience with results.', 'Naval Ravikant', ''),
  ('The three big ones in life are wealth, health, and happiness. We pursue them in that order, but their importance is reverse.', 'Naval Ravikant', ''),
  -- Zig Ziglar
  ('You don''t have to be great to start, but you have to start to be great.', 'Zig Ziglar', ''),
  ('People often say that motivation doesn''t last. Well, neither does bathing. That''s why we recommend it daily.', 'Zig Ziglar', ''),
  ('Your attitude, not your aptitude, will determine your altitude.', 'Zig Ziglar', ''),
  ('You can have everything in life you want, if you will just help other people get what they want.', 'Zig Ziglar', ''),
  ('Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.', 'Zig Ziglar', ''),
  ('Repetition is the mother of learning, the father of action, which makes it the architect of accomplishment.', 'Zig Ziglar', ''),
  ('Expect the best. Prepare for the worst. Capitalize on what comes.', 'Zig Ziglar', '')
ON CONFLICT (text) DO NOTHING;

COMMIT;
